// Mocks generated by Mockito 5.4.4 from annotations
// in ttm01_flutter_dependency_injection/test/data/models/post.model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:ttm01_flutter_dependency_injection/data/models/post.model.dart'
    as _i3;
import 'package:ttm01_flutter_dependency_injection/domain/entities/post.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePost_0 extends _i1.SmartFake implements _i2.Post {
  _FakePost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostModel extends _i1.Mock implements _i3.PostModel {
  MockPostModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: 0,
      ) as int);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.Post toEntity() => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [],
        ),
        returnValue: _FakePost_0(
          this,
          Invocation.method(
            #toEntity,
            [],
          ),
        ),
      ) as _i2.Post);
}
